# define a imagem base
FROM nginx

# define o mantenedor da imagem
LABEL maintainer="rfahham@hotmail.com"

# Copy your web content to the default Nginx public directory
COPY index.html /usr/share/nginx/html/index.html