import time

print("")
print("Contagem regressiva !!!")
print("")
time.sleep(1)
print("10", end="\r")
time.sleep(1)
print("09", end="\r")
time.sleep(1)
print("08", end="\r")
time.sleep(1)
print("07", end="\r")
time.sleep(1)
print("06", end="\r")
time.sleep(1)
print("05", end="\r")
time.sleep(1)
print("04", end="\r")
time.sleep(1)
print("03", end="\r")
time.sleep(1)
print("02", end="\r")
time.sleep(1)
print("01", end="\r")
print("")
print("Parabéns !!!")